import Head from "next/head";
import Banner from "@/components/Banner";
import { Inter } from "@next/font/google";
import Title from "@/components/Text/Title";
import SubTitle from "@/components/Text/SubTitle";
import ServiceCard from "@/components/ServiceCard";
import BlockDescRight from "@/components/Block/BlockDescRight";
import BlockDescLeft from "@/components/Block/BlockDescLeft";
import BlogLayout from "@/components/BlogLayout";
import Button from "@/components/Button/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      {/* Define Head of HTML */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* END Define Head of HTML */}

      <Banner />
      <section className="px-[30px] md:px-[50px] lg:px-[150px]">
        <div className="our-services flex justify-center text-center py-[20px] md:py-[60px] flex-col">
          <div className="our-services__title flex flex-col gap-[10px] mb-[30px]">
            <Title>Service terbaik yang di suguhkan untukmu.</Title>
            <SubTitle>Dapatkan banyak promo...</SubTitle>
          </div>
          <div className="our-service__card">
            <ServiceCard />
          </div>
        </div>
      </section>

      <section class="py-10 bg-get_navy sm:py-16 lg:py-24">
        <div class="max-w-5xl px-4 mx-auto sm:px-6 lg:px-8">
          <div class="grid grid-cols-1 md:items-stretch md:grid-cols-2 gap-x-12 lg:gap-x-20 gap-y-10">
            <div class="flex flex-col justify-between lg:py-5">
              <h2 class="text-3xl font-bold leading-tight text-white sm:text-4xl lg:leading-tight lg:text-5xl">
                Penawaran khusus untuk kamu yang melihatnya dihari ini.
              </h2>

              <div class="mt-auto">
                <div class="flex items-center">
                  <svg
                    class="w-6 h-6 text-yellow-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                  </svg>
                  <svg
                    class="w-6 h-6 text-yellow-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                  </svg>
                  <svg
                    class="w-6 h-6 text-yellow-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                  </svg>
                  <svg
                    class="w-6 h-6 text-yellow-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                  </svg>
                  <svg
                    class="w-6 h-6 text-yellow-500"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                  </svg>
                </div>

                <blockquote class="mt-6">
                  <p class="text-lg leading-relaxed text-white">
                    Beli dihari ini juga sebelum kamu kehilangan kesempatan yang
                    berharga ini.
                  </p>
                </blockquote>
              </div>
            </div>

            <div class="">
              <div class="overflow-hidden bg-white rounded-md">
                <div class="p-10">
                  <h3 class="text-xs tracking-widest text-get_pink uppercase font-bold">
                    Paket Promo Langganan Pertama
                  </h3>
                  <p class="mt-4 text-6xl font-bold text-black">Rp. 999K</p>

                  <ul class="flex flex-col mt-8 space-y-4">
                    <li class="inline-flex items-center space-x-2">
                      <svg
                        class="flex-shrink-0 w-5 h-5 text-green-500"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                      >
                        <path
                          fill-rule="evenodd"
                          d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                          clip-rule="evenodd"
                        />
                      </svg>
                      <span class="text-base font-medium text-gray-900">
                        {" "}
                        2 Treatment Home Care{" "}
                      </span>
                    </li>

                    <li class="inline-flex items-center space-x-2">
                      <svg
                        class="flex-shrink-0 w-5 h-5 text-green-500"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                      >
                        <path
                          fill-rule="evenodd"
                          d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                          clip-rule="evenodd"
                        />
                      </svg>
                      <span class="text-base font-medium text-gray-900">
                        {" "}
                        1 TeleFisio{" "}
                      </span>
                    </li>

                    <li class="inline-flex items-center space-x-2">
                      <svg
                        class="flex-shrink-0 w-5 h-5 text-green-500"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                      >
                        <path
                          fill-rule="evenodd"
                          d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                          clip-rule="evenodd"
                        />
                      </svg>
                      <span class="text-base font-medium text-gray-900">
                        {" "}
                        4 Online Consultation{" "}
                      </span>
                    </li>

                    <li class="inline-flex items-center space-x-2">
                      <svg
                        class="flex-shrink-0 w-5 h-5 text-green-500"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                      >
                        <path
                          fill-rule="evenodd"
                          d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                          clip-rule="evenodd"
                        />
                      </svg>
                      <span class="pb-0.5 text-base font-medium text-gray-900 border-b border-black border-dashed">
                        {" "}
                        3 hari Premium Access Exercise Video{" "}
                      </span>
                    </li>
                  </ul>

                  <Button
                    classButton="bg-get_pink py-[18px] px-[20px] mt-[20px]"
                    title="Pesan Sekarang!"
                  ></Button>

                  <div class="flex items-center mt-5">
                    <svg
                      class="flex-shrink-0 w-5 h-5 text-gray-500"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
                      />
                    </svg>
                    <span class="ml-2 text-sm text-gray-500">
                      {" "}
                      Syarat dan ketentuan berlaku.{" "}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="px-[30px] md:px-[50px] lg:px-[150px]">
        <BlockDescRight />
      </section>
      <section className="px-[30px] md:px-[50px] lg:px-[150px]">
        <BlockDescLeft />
      </section>

      <section className="px-[30px] md:px-[50px] lg:px-[150px] py-[60px] ">
        <div className="our-blogs flex justify-center text-center  flex-col">
          <div className="our-blogs__title flex flex-col gap-[10px] mb-[30px]">
            <Title>Dapatkan Artikel menarik dari Get Fisio.</Title>
            <SubTitle>Pengetahuan itu penting untuk kesehatan loh.</SubTitle>
          </div>
        </div>
        <BlogLayout />
      </section>

      <section className="px-[30px] md:px-[50px] lg:px-[150px] py-[60px]">
        <div class="max-w-5xl px-4 mx-auto sm:px-6 lg:px-8">
          <div className="our-client flex justify-center text-center  flex-col">
            <div className="our-client__title flex flex-col gap-[10px] mb-[30px]">
              <Title>Klien Kami.</Title>
              <SubTitle>
                Klien yang telah merasakan manfaat layanan kami.
              </SubTitle>
            </div>
          </div>

          <div class="grid items-center grid-cols-2 gap-10 mt-12 md:grid-cols-4 sm:gap-y-16">
            <div>
              <img
                class="object-contain w-auto mx-auto h-14"
                src="https://cdn.rareblocks.xyz/collection/celebration/images/logos/2/logo-1.png"
                alt=""
              />
            </div>

            <div>
              <img
                class="object-contain w-auto mx-auto h-14"
                src="https://cdn.rareblocks.xyz/collection/celebration/images/logos/2/logo-2.png"
                alt=""
              />
            </div>

            <div>
              <img
                class="object-contain w-auto h-10 mx-auto"
                src="https://cdn.rareblocks.xyz/collection/celebration/images/logos/2/logo-3.png"
                alt=""
              />
            </div>

            <div>
              <img
                class="object-contain w-auto mx-auto h-14"
                src="https://cdn.rareblocks.xyz/collection/celebration/images/logos/2/logo-4.png"
                alt=""
              />
            </div>
          </div>
        </div>
      </section>

      <section className="px-[30px] md:px-[50px] lg:px-[150px] py-[60px] bg-get_navy">
        <div class="px-4 mx-auto sm:px-6 lg:px-8 max-w-7xl">
          <div className="subscription flex justify-center text-center  flex-col">
            <div className="subscription__title flex flex-col gap-[10px] mb-[30px]">
              <Title classText="text-white">Tetap terhubung</Title>
              <SubTitle classText="text-white">
                jangan lewatkan kesempatan untuk tetap update hal baru dari
                kami.
              </SubTitle>
            </div>
          </div>

          <form action="#" method="POST" class="max-w-xl mx-auto mt-12">
            <div class="flex flex-col items-center sm:flex-row sm:justify-center gap-[20px]">
              <div class="flex-1 w-full min-w-0 px-4 sm:px-0 h-full">
                <label for="email" class="sr-only"></label>
                <input
                  className=" py-[5px] px-[10px]  rounded-lg h-full w-full"
                  type="email"
                  name="email"
                  id="email"
                  placeholder="Enter email to get started"
                  class="block w-full px-4 py-4 text-base text-black placeholder-gray-500 transition-all duration-200 border-transparent rounded-md caret-indigo-600 outline-get_blue focus:outline-get_pink active:ring-get_pink "
                  required
                />
              </div>
              <div className="w-1/2 h-full">
                <Button
                  classButton="h-full bg-get_pink py-[17px] px-[10px]"
                  title="Kirim"
                />
              </div>
            </div>
          </form>

          <div class="flex items-center justify-center px-8 mt-8 sm:px-0">
            <svg
              class="flex-shrink-0 w-5 h-5 text-white"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="1.5"
                d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
              />
            </svg>
            <span class="ml-2 text-sm text-white">
              {" "}
              Data kamu akan dilindungi, dan kami tidak akan membagikannya
              dengan siapapun.{" "}
            </span>
          </div>
        </div>
      </section>
    </>
  );
}
